services:
  - type: web
    name: student-performance-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn predictor_web.predictor_web.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: predictor_web.predictor_web.settings
      - key: PYTHONUNBUFFERED
        value: '1'
